baseurl = "https://blog.networksec.in"
languageCode = "en"
title = "Security"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/vijayronan\">Vijay Ronan</a> 2020"
disqusShortname = ""
googleAnalytics = ""
# Number of posts per page
Paginate = 50
enableRobotsTXT = true

[params.rss]

includeContent = true # Includes whole content in rss
authorName = "Vijay Ronan" # Site author's full name
authorEmail = "vijay.ronan@gmail.com"


[params.social]

twitter = "vijayronan"
github = "vijayronan"
email = "vijayronan"
linkedin = "vijayronan"


[params.social.config]
platforms = ["twitter","github","email","linkedin"]


[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

